CREATE TABLE DOMAIN_EVENT_ENTRY
(
  GLOBAL_INDEX bigint PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  EVENT_IDENTIFIER varchar(255) NOT NULL,
  META_DATA blob(10000),
  PAYLOAD blob(10000) NOT NULL,
  PAYLOAD_REVISION varchar(255),
  PAYLOAD_TYPE varchar(255) NOT NULL,
  TIME_STAMP varchar(255) NOT NULL,
  AGGREGATE_IDENTIFIER varchar(255) NOT NULL,
  SEQUENCE_NUMBER bigint NOT NULL GENERATED ALWAYS AS (GLOBAL_INDEX),
  TYPE varchar(255)
);
CREATE UNIQUE INDEX UK_FWE6LSA8BFO6HYAS6UD3M8C7X ON DOMAIN_EVENT_ENTRY (EVENT_IDENTIFIER);
CREATE UNIQUE INDEX UK8S1F994P4LA2IPB13ME2XQM1W ON DOMAIN_EVENT_ENTRY (AGGREGATE_IDENTIFIER, SEQUENCE_NUMBER);
