ALTER TABLE DB2INST1.DOMAIN_EVENT_ENTRY ALTER META_DATA SET DATA TYPE BLOB(1000000);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.DOMAIN_EVENT_ENTRY');
ALTER TABLE DB2INST1.DOMAIN_EVENT_ENTRY ALTER PAYLOAD SET DATA TYPE BLOB(1000000);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.DOMAIN_EVENT_ENTRY');

ALTER TABLE DB2INST1.SNAPSHOT_EVENT_ENTRY ALTER META_DATA SET DATA TYPE BLOB(1000000);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.SNAPSHOT_EVENT_ENTRY');
ALTER TABLE DB2INST1.SNAPSHOT_EVENT_ENTRY ALTER PAYLOAD SET DATA TYPE BLOB(1000000);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.SNAPSHOT_EVENT_ENTRY');
